# Generated by Django 4.1.5 on 2023-01-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cred',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cred',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cred',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
