# Generated by Django 4.1.5 on 2023-01-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_cred_email_alter_cred_password_alter_cred_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cred',
        ),
    ]
